#
# Module manifest for module 'Unduplicator'
#
# Generated by: FallenGameR (aka Alexander Kostikov)
# Generated on: 2012-05-12
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'unduplicator.psm1'

# Version number of this module.
ModuleVersion = '0.1.1.1'

# ID used to uniquely identify this module
GUID = 'f74d2031-2ddb-441a-b50b-22520304c708'

# Author of this module
Author = 'Alexander Kostikov'

# Company or vendor of this module
CompanyName = 'None'

# Copyright statement for this module
Copyright = '(c) 2012 Alexander Kostikov'

# Description of the functionality provided by this module
Description = 'Scripts for finding duplicate files on hard drive.'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'unduplicator.ps1xml'

# List of all files packaged with this module
FileList = 
    'unduplicator.ps1xml',
    'unduplicator.psd1', 
    'unduplicator.psm1'
}
        
